const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const VIEWS={mission:'State AgriStack Mission Control',farmgraph:'FarmGraph AI · Agricultural Digital Twin',care:'CARE · Governed Reconciliation',farmer:'Farmer & Field Execution',gis:'GIS Intelligence · Rajasthan',integrations:'DPI & Integration Fabric',rollout:'90-Day Rollout & 2030 Vision',evidence:'Evidence Room'};
const DISTRICTS=[['Barmer',72,184,'Land-sync drift + offline reach'],['Banswara',78,119,'Identity / assisted-service pressure'],['Jaisalmer',76,126,'Low-connectivity validation'],['Dungarpur',80,94,'Consent + field-service readiness'],['Udaipur',87,72,'Crop / land convergence'],['Bikaner',90,61,'Irrigated service throughput'],['Jodhpur',92,58,'Mutation resolution'],['Jaipur',96,34,'High digital readiness']];
const INTEGRATIONS=[
['AgriStack Farmer Registry / UFSI','SANDBOX / CONTRACT READY','Federated farmer identity + service interface','Central / State AgriStack'],
['Crop Sown Registry','SANDBOX / CONTRACT READY','Seasonal crop assertion / DCS linkage','Agriculture / AgriStack'],
['Jan Aadhaar 2.0','CONTRACT READY','Reference-based person/household identity bridge','DoIT&C Rajasthan'],
['e-Dharti / DILRMP / RoR','PUBLIC REFERENCE + CONTRACT READY','Land relationship + sanctioned mutation source','Revenue Department'],
['Raj Sewa Dwaar','ARCHITECTURE ALIGNED','State API gateway / approved connector rail','DoIT&C Rajasthan'],
['Raj SSO','CONTRACT READY','Officer authentication + role context','DoIT&C Rajasthan'],
['Rajdharaa / LGD','REFERENCE READY','Production administrative / spatial authority','Rajasthan GIS / LGD'],
['RajKisan','CONTRACT READY','Scheme / service workflow adapter','Agriculture Department'],
['Rajasthan Sampark','ADAPTER PATTERN','Unresolved grievance escalation','Rajasthan Government'],
['BHASHINI','PROTOTYPE ADAPTER','Preferred ASR / TTS / translation rail','MeitY / Digital India'],
['SUTRA-ID Edge','REAL DEVICE CAPABILITY','Optional voice-first low-connectivity field execution','Syntheon'],
['FarmGraph AI / CARE','LIVE PROTOTYPE','Temporal relationship intelligence + governed reconciliation','RAJ-AGRISETU X']
];
const DEMO=[
{view:'mission',title:'Detect the mismatch',text:'Start from Rajasthan’s operating context: Farmer-ID scale exists, but land relationships can drift after mutation.',stage:'detect'},
{view:'farmgraph',title:'FarmGraph explains the drift',text:'The graph identifies the missing Farmer Registry ↔ parcel edge without pretending AI can rewrite the source.',stage:'graph'},
{view:'farmer',title:'Farmer verifies offline',text:'The Hindi-first PWA captures the farmer assertion offline and later receives only a server acknowledgement — not approval.',stage:'farmer'},
{view:'care',title:'Human authority resolves it',text:'CARE compares source facts, farmer assertion and AI observation; an authorized role decides.',stage:'care'},
{view:'mission',title:'Purpose consent + scheme trace',text:'The demo then limits data use to a clear purpose and runs a deterministic non-statutory scheme pre-check.',stage:'consent'},
{view:'rollout',title:'Prototype → production core',text:'The 90-day plan replaces synthetic data and contract adapters with approved integrations, field validation and operational SLAs.',stage:'rollout'}
];
let demoIndex=0,careApproved=false,consentActive=false;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('on');setTimeout(()=>x.classList.remove('on'),1900)}
function showView(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+name)?.classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent=VIEWS[name]||'RAJ-AGRISETU X';window.scrollTo({top:0,behavior:'smooth'})}
$$('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
function stageHtml(kind){
 if(kind==='detect')return `<div class="stage-grid"><div class="stage-card"><strong>Farmer Registry</strong><span>2 parcels</span><small>synthetic evaluator snapshot</small></div><div class="stage-card"><strong>RoR / sanctioned mutation</strong><span>3 parcels</span><small>authoritative-source pattern</small></div></div><div class="stage-callout">The innovation starts after registration: the system notices that a land mutation changed reality but the farmer relationship graph has not caught up.</div><div class="stage-actions"><button class="btn primary" data-stage-go="farmgraph">Explain with FarmGraph AI</button></div>`;
 if(kind==='graph')return `<div class="stage-grid"><div class="stage-card"><strong>Conflict identified</strong><span>Missing edge: Farmer ID → Khasra 214/3</span><small>source-aware temporal relationship</small></div><div class="stage-card"><strong>AI authority</strong><span>Detect · explain · prioritize</span><small>cannot mutate registry</small></div></div><div class="stage-callout">FarmGraph AI is a digital-twin relationship layer, not a new master database. It knows what disagrees, why it disagrees and who must resolve it.</div><div class="stage-actions"><button class="btn primary" data-stage-go="farmer">Verify with farmer</button></div>`;
 if(kind==='farmer')return `<div class="stage-grid"><div class="stage-card"><strong>Offline transaction</strong><span>Assertion stored locally</span><small>queue survives connectivity loss</small></div><div class="stage-card"><strong>Reconnect</strong><span>Server ACK → CARE</span><small>ACK ≠ verification</small></div></div><div class="stage-callout">The required farmer mobile experience is real and installable. SUTRA is optional for camps, voice-first access and low-connectivity edge cases.</div><div class="stage-actions"><a class="btn primary" href="/kisan" target="_blank">Open Farmer PWA ↗</a><button class="btn" data-stage-go="care">Continue to CARE</button></div>`;
 if(kind==='care')return `<div class="stage-grid"><div class="stage-card"><strong>Source facts</strong><span>Registry 2 · RoR 3</span><small>kept immutable in evaluator</small></div><div class="stage-card"><strong>Required authority</strong><span>District Verifier</span><small>AI cannot decide</small></div></div><div class="stage-callout">CARE turns disagreement into a case with an explicit human authority boundary and a receipt. No source system changes silently.</div><div class="stage-actions"><button class="btn primary" data-stage-care>Approve demo reconciliation</button><button class="btn" data-stage-go="care">Open workbench</button></div>`;
 if(kind==='consent')return `<div class="stage-grid"><div class="stage-card"><strong>Purpose consent</strong><span>${consentActive?'ACTIVE · identity + parcel + crop':'24h · identity + parcel + crop'}</span><small>bank/family data excluded</small></div><div class="stage-card"><strong>Scheme Compiler</strong><span>${careApproved&&consentActive?'PRE-CHECK READY':'governed inputs required'}</span><small>deterministic · non-statutory</small></div></div><div class="stage-callout">A service receives only what its approved purpose needs. AI explains the result; deterministic rules produce the trace; the authorized scheme workflow makes the real decision.</div><div class="stage-actions"><button class="btn primary" data-stage-consent>${consentActive?'Consent active':'Grant demo consent'}</button><button class="btn" data-stage-scheme>Run scheme pre-check</button></div>`;
 return `<div class="stage-grid"><div class="stage-card"><strong>Prototype proves now</strong><span>governed workflows end-to-end</span><small>synthetic data + deterministic APIs</small></div><div class="stage-card"><strong>90-day core adds</strong><span>approved integrations + field UAT</span><small>production security + SLAs</small></div></div><div class="stage-callout">We are not pretending this prototype is already the State production system. We are showing Rajasthan exactly what is already de-risked and what the proposed implementation funds.</div><div class="stage-actions"><button class="btn primary" data-stage-go="rollout">See implementation plan</button></div>`;
}
function bindStage(){$$('[data-stage-go]').forEach(b=>b.onclick=()=>showView(b.dataset.stageGo));const c=$('[data-stage-care]');if(c)c.onclick=()=>approveCare();const s=$('[data-stage-consent]');if(s)s.onclick=()=>{consentActive=true;toast('Purpose consent activated for evaluator session');renderDemoStage('consent')};const r=$('[data-stage-scheme]');if(r)r.onclick=()=>{if(!careApproved)return toast('CARE human approval required first');if(!consentActive)return toast('Purpose consent required first');toast('Deterministic pre-check: READY · final eligibility remains with scheme authority');renderDemoStage('consent')}}
function renderDemoStage(kind){$('#demoStage').innerHTML=stageHtml(kind);bindStage()}
renderDemoStage('detect');
$$('[data-demo-step]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.demoStep);$$('[data-demo-step]').forEach(x=>x.classList.toggle('active',x===b));renderDemoStage(DEMO[i].stage)});
function openDemo(){demoIndex=0;$('#demoRail').classList.add('on');renderDemo();}
function renderDemo(){const d=DEMO[demoIndex];$('#demoCounter').textContent=(demoIndex+1)+' / '+DEMO.length;$('#demoTitle').textContent=d.title;$('#demoText').textContent=d.text;$('#demoPrev').disabled=demoIndex===0;$('#demoNext').textContent=demoIndex===DEMO.length-1?'Finish':'Next';showView(d.view);if(d.view==='mission')renderDemoStage(d.stage)}
$('#startDemo').onclick=openDemo;$('#demoLaunchInline').onclick=openDemo;$('#demoPrev').onclick=()=>{if(demoIndex>0){demoIndex--;renderDemo()}};$('#demoNext').onclick=()=>{if(demoIndex===DEMO.length-1){$('#demoRail').classList.remove('on');showView('mission');toast('Guided prototype journey complete')}else{demoIndex++;renderDemo()}};$('#demoClose').onclick=()=>$('#demoRail').classList.remove('on');
async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function approveCare(){try{const out=await post('/api/care',{caseId:'CARE-RAJ-2026-001284',action:'APPROVE'});careApproved=true;if(out.approvalArtifact)localStorage.setItem('rajAgriCareApproval',JSON.stringify(out.approvalArtifact));$('#careStatus').textContent='APPROVED · EVALUATOR';$('#careStatus').className='pill';$('#careReceipt').className='receipt-live';$('#careReceipt').innerHTML=`<code>${out.receipt.eventId}</code><b>${out.state}</b><br>${out.notice}<br><br><strong>Next:</strong> ${out.propagation.next} · ${out.propagation.status}`;toast('CARE human-approval receipt generated');renderDemoStage('care')}catch(e){careApproved=true;const artifact={artifactType:'CARE_HUMAN_APPROVAL',farmerId:'RAJ-FID-000284',careCaseId:'CARE-RAJ-2026-001284',verifiedParcelRelationship:true,verifiedParcelCount:3,receiptId:'LOCAL-EVALUATOR-'+Date.now().toString(36).toUpperCase(),approvedAt:new Date().toISOString(),scope:'EVALUATOR_SESSION_ONLY'};localStorage.setItem('rajAgriCareApproval',JSON.stringify(artifact));$('#careStatus').textContent='APPROVED · LOCAL DEMO';$('#careReceipt').className='receipt-live';$('#careReceipt').innerHTML=`<code>${artifact.receiptId}</code><b>APPROVED</b><br>Local evaluator fallback. No Government source record changed.`;toast('CARE evaluator fallback receipt generated')}}
$('#careApprove').onclick=approveCare;$('#careEvidence').onclick=()=>toast('Evidence request recorded · source state unchanged');$('#careReject').onclick=()=>{$('#careStatus').textContent='REJECTED · EVALUATOR';$('#careStatus').className='pill risk';$('#careReceipt').className='receipt-live';$('#careReceipt').innerHTML='<code>EVT-REJECT-'+Date.now().toString(36).toUpperCase()+'</code><b>REJECTED</b><br>Evaluator decision only. No Government source record changed.';toast('CARE case rejected in evaluator session')};
$('#resetBtn').onclick=()=>{localStorage.removeItem('rajAgriCareApproval');careApproved=false;consentActive=false;$('#careStatus').textContent='NEEDS REVIEW';$('#careStatus').className='pill risk';$('#careReceipt').className='empty-state';$('#careReceipt').textContent='No official decision in this evaluator session.';renderDemoStage('detect');showView('mission');toast('Evaluator state reset')};
$('#districtRanking').innerHTML=DISTRICTS.map(([d,h,c,n])=>`<div class="rank-row"><div><b>${d}</b><span>${c} synthetic CARE cases · ${n}</span></div><strong>${h}</strong></div>`).join('');
$('#integrationGrid').innerHTML=INTEGRATIONS.map(x=>`<article class="integration-card"><small>${x[1]}</small><h3>${x[0]}</h3><p>${x[2]}</p><b>Authority / owner: ${x[3]}</b></article>`).join('');
async function health(){try{const r=await fetch('/api/health',{cache:'no-store'});const out=await r.json();$('#apiDot').style.background='#31ad78';$('#apiState').textContent='Prototype services healthy';$('#apiSub').textContent=out.version||'evaluator API';return out}catch(e){$('#apiDot').style.background='#d39a45';$('#apiState').textContent='Static prototype mode';$('#apiSub').textContent='API unavailable';return null}}
$('#pingApi').onclick=async()=>{$('#apiOutput').textContent='Checking…';const out=await health();$('#apiOutput').textContent=JSON.stringify(out||{status:'static_fallback',notice:'Prototype UI remains explorable; no Government integration is implied.'},null,2)};
health();
