const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DISTRICTS=['Ajmer','Alwar','Balotra','Banswara','Baran','Barmer','Beawar','Bharatpur','Bhilwara','Bikaner','Bundi','Chittorgarh','Churu','Dausa','Deeg','Dholpur','Didwana-Kuchaman','Dungarpur','Hanumangarh','Jaipur','Jaisalmer','Jalore','Jhalawar','Jhunjhunu','Jodhpur','Karauli','Khairthal-Tijara','Kota','Kotputli-Behror','Nagaur','Pali','Phalodi','Pratapgarh','Rajsamand','Salumber','Sawai Madhopur','Sikar','Sirohi','Sri Ganganagar','Tonk','Udaipur'];
const SEEDED={Barmer:[94,88,91,97,82,72,184],Jaisalmer:[95,91,89,98,84,76,126],Jodhpur:[98,96,95,98,93,92,58],Jaipur:[99,98,97,99,97,96,34],Bikaner:[97,95,94,98,90,90,61],Udaipur:[96,94,92,97,86,87,72],Kota:[98,97,96,99,95,94,41],Banswara:[94,90,88,96,81,78,119],Ajmer:[97,96,94,98,92,91,52],Alwar:[96,93,92,97,89,86,73]};
const CASES=[
 {id:'CARE-001284',district:'Barmer',type:'LAND_MUTATION',exception:'Farmer Registry 2 vs RoR 3 parcels',age:11,priority:'HIGH',authority:'District Verifier'},
 {id:'CARE-001219',district:'Banswara',type:'IDENTITY_DRIFT',exception:'Name + relation mismatch',age:9,priority:'MEDIUM',authority:'Tehsil Verifier'},
 {id:'CARE-001178',district:'Jaisalmer',type:'CROP_CONFLICT',exception:'Farmer assertion vs survey',age:8,priority:'MEDIUM',authority:'Agriculture Officer'},
 {id:'CARE-001142',district:'Barmer',type:'LAND_MUTATION',exception:'Mutation awaiting registry sync',age:7,priority:'HIGH',authority:'District Verifier'},
 {id:'CARE-001097',district:'Jodhpur',type:'LAND_MUTATION',exception:'Parcel relationship changed',age:5,priority:'MEDIUM',authority:'District Verifier'}
];
const DEPARTMENTS=[
 ['Revenue / e-Dharti','PUBLIC + CONTRACT','RoR / mutation authority'],['Agriculture / AgriStack','SANDBOX','Farmer + Crop registries'],['Jan Aadhaar 2.0','CONTRACT READY','person/household identity bridge'],['Raj Sewa Dwaar','CONTRACT READY','State API gateway'],['Rajdharaa / LGD','REFERENCE READY','administrative/spatial authority'],['Water Resources','REFERENCE READY','policy-bound irrigation/water context'],['Cooperatives / FPO','ADAPTER PATTERN','assisted/member service context']
];
const INTEGRATIONS=[
 ['Farmer Registry / UFSI','SANDBOX','Central/State AgriStack','Federated farmer identity adapter'],['Crop Sown Registry','SANDBOX','AgriStack / State','Seasonal crop assertion adapter'],['Jan Aadhaar 2.0','CONTRACT READY','DoIT&C Rajasthan','Reference-based identity bridge'],['e-Dharti / DILRMP','PUBLIC + CONTRACT','Revenue Department','RoR / mutation source'],['Raj Sewa Dwaar','CONTRACT READY','DoIT&C Rajasthan','API gateway / subscription / policy rail'],['Raj SSO','CONTRACT READY','DoIT&C Rajasthan','Officer authentication / role context'],['RajMasters','PUBLIC REFERENCE','Rajasthan Government','current administrative master'],['Rajdharaa / LGD','REFERENCE READY','State GIS / DoIT&C','production geographic authority'],['RajKisan','CONTRACT READY','Agriculture Department','scheme/service workflow adapter'],['Rajasthan Sampark','ADAPTER PATTERN','Rajasthan Government','unresolved grievance escalation'],['BHASHINI','PROTOTYPE ADAPTER','MeitY / Digital India','ASR/TTS/translation rail'],['SUTRA-ID Edge','LIVE PROTOTYPE','Syntheon','optional field/offline/voice execution']
];
const CONTROLS=[
 ['RBAC & scope','State / District / Field roles','District role is locked to Barmer; field role is limited to assigned/field surfaces.'],['Purpose policy','Scope + duration + exclusions','Consent is minimal, revocable and never assumed from a generic checkbox.'],['Source separation','Fact / assertion / decision','Farmer assertion cannot silently overwrite Farmer Registry or RoR.'],['Offline integrity','Local queue → ACK → CARE','Queue entry is removed only after server acknowledgement.'],['Audit & receipts','Event IDs + authority boundary','CARE, consent, sync and policy actions create evaluator receipts.'],['Integration truth','No fake green connections','Sandbox, public reference, contract-ready and prototype states remain distinct.'],['Data minimization','Reference, not duplicate master','Jan Aadhaar/RoR/registry data remains with authoritative systems.'],['Production hosting','Department-approved environment','Evaluator APIs prove contracts; they are not authoritative Government services.'],['AI boundary','Advisory, not statutory','AI may explain/rank; it may not mutate records or approve benefits.']
];
let state={role:'state',district:'all',exception:'all',consentId:null,careDecision:null};
let audits=[['14:18','Policy Engine','PURPOSE_SCOPE_VALIDATED','scheme-precheck · identity/parcel/crop'],['14:16','District Verifier','CARE_CASE_OPENED','CARE-001284 · Barmer'],['14:12','Offline Sync','QUEUE_ACKNOWLEDGED','OFF-RAJ-82A1'],['14:09','SahmatiOS','CONSENT_NOTICE_RENDERED','hi-IN · voice + text']];
function demoMetrics(name,index){const x=SEEDED[name]||[94+(index%5),91+(index*3%7),90+(index*5%8),96+(index%4),83+(index*7%12),80+(index*11%15),45+(index*17%89)];return {name,registry:x[0],land:x[1],crop:x[2],consent:x[3],offline:x[4],health:x[5],cases:x[6]}}
const ROWS=DISTRICTS.map(demoMetrics);
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('on');setTimeout(()=>x.classList.remove('on'),1800)}
function statusClass(v){return v>=88?'good':v>=78?'warn':'risk'}
function scopedDistrict(){return state.role==='state'?state.district:'Barmer'}
function scopedRows(){const d=scopedDistrict();return d==='all'?ROWS:ROWS.filter(x=>x.name===d)}
function scopedCases(){let rows=CASES.filter(c=>state.role==='state'||c.district==='Barmer');const d=scopedDistrict();if(d!=='all')rows=rows.filter(c=>c.district===d);if(state.exception==='high')rows=rows.filter(c=>c.priority==='HIGH');if(state.exception==='land')rows=rows.filter(c=>c.type==='LAND_MUTATION');if(state.exception==='identity')rows=rows.filter(c=>c.type==='IDENTITY_DRIFT');return rows}
function page(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+view).classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={overview:'State AgriStack Operations Overview',districts:'District Rollout Control',care:'CARE Reconciliation Workbench',consent:'Consent Ledger & Policy Trace',field:'Farmer & Field Operations',integrations:'Cross-Department Integration Fabric',governance:'Security & Governance Control Plane',reports:'Reports & Audit'};$('#pageTitle').textContent=titles[view];window.scrollTo({top:0,behavior:'smooth'})}
$$('#nav button').forEach(b=>b.onclick=()=>{if(state.role==='field'&&!['field','care','reports'].includes(b.dataset.view))return toast('Field Operator demo scope is limited to assigned field/case surfaces');page(b.dataset.view)});$$('[data-go]').forEach(b=>b.onclick=()=>page(b.dataset.go));
function renderDistrictOptions(){const select=$('#districtFilter');select.innerHTML='<option value="all">All 41 districts</option>'+DISTRICTS.map(d=>`<option>${d}</option>`).join('');if(state.role!=='state'){select.value='Barmer';select.disabled=true}else{select.disabled=false;select.value=state.district}}
function renderKpis(){const rows=scopedRows();const cases=scopedCases();const districtLabel=scopedDistrict()==='all'?'41':'1';$('#kDistrict').textContent=districtLabel;$('#kCare').textContent=cases.reduce((a,c)=>a+1,0)+(scopedDistrict()==='all'?' / 1,284 statewide':' scoped');const avg=k=>Math.round(rows.reduce((a,r)=>a+r[k],0)/Math.max(rows.length,1)*10)/10;$('#kConsent').textContent=avg('consent')+'%';$('#kOffline').textContent=avg('offline')+'%';$('#scopeStamp').textContent=state.role==='state'?(scopedDistrict()==='all'?'State scope · 41 districts':'State role · filtered to '+scopedDistrict()):state.role==='district'?'District Officer scope · Barmer':'Field Operator scope · Barmer assignments';$('#rolloutTitle').textContent=scopedDistrict()==='all'?'District Readiness & Exception Matrix':scopedDistrict()+' Readiness & Exception Matrix'}
function renderRollout(){const rows=scopedRows();$('#rolloutRows').innerHTML=rows.map(r=>`<tr><td><strong>${r.name}</strong></td><td>${r.registry}%</td><td>${r.land}%</td><td>${r.crop}%</td><td>${r.consent}%</td><td>${r.offline}%</td><td><span class="score"><i class="${statusClass(r.health)}"></i>${r.health}</span></td><td>${r.cases}</td><td><button class="row-action" data-district-open="${r.name}">Open</button></td></tr>`).join('');$$('[data-district-open]').forEach(b=>b.onclick=()=>{if(state.role!=='state'&&b.dataset.districtOpen!=='Barmer')return toast('Outside current role scope');state.district=b.dataset.districtOpen;renderDistrictOptions();renderAll();page('districts')})}
function renderCases(){const cases=scopedCases();$('#caseRows').innerHTML=cases.map(c=>`<tr><td>${c.id}</td><td>${c.district}</td><td>${c.exception}</td><td>${c.age}d</td><td><span class="status ${c.priority==='HIGH'?'risk':'warn'}">${c.priority}</span></td><td>${c.authority}</td><td><button class="row-action" data-case-open="${c.id}">Dispose</button></td></tr>`).join('');$('#careRows').innerHTML=cases.map(c=>`<tr><td>${c.id}</td><td>${c.district}</td><td>${c.type}</td><td>${c.exception}</td><td>${c.age}d</td><td><span class="status ${c.priority==='HIGH'?'risk':'warn'}">${c.priority}</span></td><td>${c.authority}</td><td><button class="row-action" data-case-open="${c.id}">Open</button></td></tr>`).join('');$$('[data-case-open]').forEach(b=>b.onclick=()=>{const c=CASES.find(x=>x.id===b.dataset.caseOpen);if(!c)return;if(state.role!=='state'&&c.district!=='Barmer')return toast('Outside current role scope');$('#activeCaseId').textContent=c.id;$('#activeDistrict').textContent=c.district;page('care')});$('#navCaseCount').textContent=state.role==='state'?'1,284':String(cases.length)}
function renderAlerts(){const c=scopedCases();const alerts=[];if(c.some(x=>x.age>=10))alerts.push(['SLA risk · oldest CARE case',c.find(x=>x.age>=10)?.id+' requires disposal','now','']);if(scopedDistrict()==='all'||scopedDistrict()==='Barmer')alerts.push(['Barmer · land-sync backlog','Mutation-linked exceptions above demo threshold','6m','warn']);alerts.push(['Offline queue watch','Field transactions awaiting acknowledgement','11m','warn']);$('#alerts').innerHTML=alerts.map(a=>`<div class="alert-item"><i class="${a[3]}"></i><div><strong>${a[0]}</strong><span>${a[1]}</span></div><time>${a[2]}</time></div>`).join('');$('#alertCount').textContent=alerts.length}
function renderDepartments(){$('#deptHealth').innerHTML=DEPARTMENTS.slice(0,6).map((d,i)=>`<div class="service-item"><div><strong>${d[0]}</strong><span>${d[2]}</span></div><span class="status ${i<2?'good':'neutral'}">${d[1]}</span></div>`).join('')}
function renderProvenance(){$('#provenance').innerHTML=[['Farmer ID progress','87,23,010 · PIB/MoA&FW · 20 Jul 2026'],['Administrative scope','41 districts · RajMasters-compatible current master'],['Land readiness','424/425 online tehsils · e-Dharti'],['Data class rule','Operational district metrics = SYNTHETIC DEMO']].map(x=>`<div class="prov-item"><div><strong>${x[0]}</strong><span>${x[1]}</span></div></div>`).join('')}
function renderActivity(){$('#activity').innerHTML=audits.slice(0,5).map(a=>`<div class="activity-item"><i></i><div><strong>${a[1]} · ${a[2]}</strong><span>${a[3]}</span></div><time>${a[0]}</time></div>`).join('');$('#auditRows').innerHTML=audits.map(a=>`<div class="audit-row"><span>${a[0]}</span><strong>${a[1]}</strong><span>${a[2]}</span><code>${a[3]}</code></div>`).join('')}
function renderDistrictList(){const rows=[...ROWS].filter(r=>scopedDistrict()==='all'||r.name===scopedDistrict()).sort((a,b)=>a.health-b.health);$('#districtList').innerHTML=rows.map(r=>`<div class="district-row"><div><strong>${r.name}</strong><span>${r.cases} synthetic open cases · land ${r.land}%</span></div><span class="status ${statusClass(r.health)}">${r.health}</span><button class="row-action" data-district-case="${r.name}">Cases</button></div>`).join('');$('#districtListTitle').textContent=scopedDistrict()==='all'?'Risk-first readiness ranking':scopedDistrict()+' readiness';$('#districtCountBadge').textContent=rows.length+'/'+(scopedDistrict()==='all'?41:1);$$('[data-district-case]').forEach(b=>b.onclick=()=>{state.district=b.dataset.districtCase;state.exception='all';renderDistrictOptions();renderAll();page('care')})}
function renderIntegrations(){$('#integrationGrid').innerHTML=INTEGRATIONS.map(x=>`<article class="integration-card"><small>${x[1]}</small><h3>${x[0]}</h3><p>${x[3]}</p><span class="owner">Authority / owner: ${x[2]}</span></article>`).join('')}
function renderGovernance(){$('#governanceGrid').innerHTML=CONTROLS.map(x=>`<article class="control-card"><small>${x[0].toUpperCase()}</small><h3>${x[1]}</h3><p>${x[2]}</p><b>CONTROL ACTIVE IN DESIGN</b></article>`).join('')}
function renderAll(){renderKpis();renderRollout();renderCases();renderAlerts();renderDepartments();renderProvenance();renderActivity();renderDistrictList();renderIntegrations();renderGovernance()}
$('#roleSelect').onchange=e=>{state.role=e.target.value;if(state.role!=='state')state.district='Barmer';else state.district='all';renderDistrictOptions();renderAll();if(state.role==='field')page('field');else page('overview');toast(state.role==='state'?'State-wide evaluator scope':'Role scope applied: Barmer')};$('#districtFilter').onchange=e=>{state.district=e.target.value;renderAll()};$('#exceptionFilter').onchange=e=>{state.exception=e.target.value;renderAll()};$('#refreshBtn').onclick=async()=>{await hydrate();renderAll();toast('Baselines refreshed; synthetic evaluator data remains labelled')};
async function api(path,opt){try{const r=await fetch(path,opt);if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}catch(e){return null}}
async function hydrate(){const [h,o]=await Promise.all([api('/api/health'),api('/api/state-overview')]);if(h){$('#apiState').textContent='API '+h.status;$('#apiDot').style.background='#21a66f'}else{$('#apiState').textContent='API fallback';$('#apiDot').style.background='#d39a45'}if(o){$('#kFarmer').textContent=(o.baseline.verified.farmerIds.value/100000).toFixed(2)+'L';$('#kTehsil').textContent=o.baseline.verified.eDhartiOnlineTehsils.value+'/'+o.baseline.verified.eDhartiOnlineTehsils.total}}
$$('[data-care]').forEach(b=>b.onclick=async()=>{if(state.role==='field')return toast('Field Operator cannot dispose CARE decisions');const action=b.dataset.care;const out=await api('/api/care',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});if(!out)return toast('CARE API unavailable; no state changed');state.careDecision=out.state;$('#activeCaseState').textContent=out.state;$('#activeCaseState').className='status '+(out.state==='APPROVED'?'good':out.state==='REJECTED'?'risk':'warn');$('#decisionCell').innerHTML=`<span class="status ${out.state==='APPROVED'?'good':out.state==='REJECTED'?'risk':'warn'}">${out.state}</span>`;$('#careReceipt').className='receipt-box';$('#careReceipt').innerHTML=`<code>${out.receipt.eventId}</code><strong>${out.state}</strong><br>${out.notice}<br>Next: ${out.propagation?.next||'CARE_CASE'} · ${out.propagation?.status||''}`;audits.unshift([new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),'District Verifier','CARE_'+out.state,$('#activeCaseId').textContent]);renderActivity();toast('CARE decision receipt generated')});
$('#grantConsent').onclick=async()=>{const out=await api('/api/consent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'GRANT',purpose:'SCHEME_PRECHECK',scope:['identity','parcel','crop'],durationHours:24,language:'hi-IN',modality:['text','voice']})});if(!out)return toast('Consent policy service unavailable');state.consentId=out.consentId;$('#consentState').textContent='ACTIVE · 24H';$('#consentState').className='status good';$('#consentReceipt').className='receipt-box';$('#consentReceipt').innerHTML=`<code>${out.consentId}</code><strong>Purpose:</strong> ${out.purpose}<br><strong>Scope:</strong> ${out.scope.join(' · ')}<br><strong>Expires:</strong> ${new Date(out.expiresAt).toLocaleString()}<br><strong>Excluded:</strong> ${out.notice.dataExcluded.join(' · ')}<br>${out.legalNote}`;audits.unshift([new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),'SahmatiOS','CONSENT_GRANTED',out.consentId]);renderActivity();toast('Purpose-bound consent issued')};
$('#revokeConsent').onclick=async()=>{if(!state.consentId)return toast('No active consent to revoke');const out=await api('/api/consent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'REVOKE',consentId:state.consentId})});if(!out)return toast('Consent policy service unavailable');$('#consentState').textContent='REVOKED';$('#consentState').className='status risk';$('#consentReceipt').innerHTML=`<code>${out.consentId}</code><strong>REVOKED</strong><br>${out.legalNote}`;audits.unshift([new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),'SahmatiOS','CONSENT_REVOKED',out.consentId]);state.consentId=null;renderActivity();toast('Consent revoked')};
$('#injectCase').onclick=()=>{CASES.unshift({id:'CARE-'+Date.now().toString().slice(-6),district:'Barmer',type:'LAND_MUTATION',exception:'Synthetic mutation changed parcel relationship',age:0,priority:'HIGH',authority:'District Verifier'});renderAll();toast('Synthetic mutation ingested into CARE')};
$('#pingApi').onclick=async()=>{$('#apiOutput').textContent='Checking…';const out=await api('/api/health');$('#apiOutput').textContent=JSON.stringify(out||{status:'unavailable',note:'No Government connectivity implied.'},null,2)};
function csv(name,rows){const text=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#exportDistricts').onclick=$('#reportDistricts').onclick=()=>csv('raj-agrisetu-district-readiness-demo.csv',[['District','Registry','Land Sync','Crop Survey','Consent','Offline','Health','Open Cases'],...scopedRows().map(r=>[r.name,r.registry,r.land,r.crop,r.consent,r.offline,r.health,r.cases])]);$('#reportCare').onclick=()=>csv('raj-agrisetu-care-ledger-demo.csv',[['Case','District','Type','Exception','Age','Priority','Authority'],...scopedCases().map(c=>[c.id,c.district,c.type,c.exception,c.age,c.priority,c.authority])]);$('#reportIntegrations').onclick=()=>csv('raj-agrisetu-integration-truth.csv',[['System','Truth State','Authority','Role'],...INTEGRATIONS]);$('#appendAudit').onclick=()=>{audits.unshift([new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),'Policy Engine','AUTHORITY_BOUNDARY_CHECK','purpose · source · role · human decision']);renderActivity();toast('Demo audit event appended')};
const map=$('#rajasthanMap');map.onerror=()=>{map.style.display='none';$('#mapFallback').style.display='block'};
const WALK=[['Real Rajasthan operating context','87.23L Farmer IDs, 41 current districts and 424/425 e-Dharti online tehsils establish the verified baseline.'],['Officer-first MIS','The first screen is rollout quality, pendency, source provenance and integration health—not a marketing hero or decorative map.'],['Role and district scope','State, District and Field roles visibly change the operational scope. District Officer is constrained to Barmer in evaluator mode.'],['Transactional offline farmer workflow','The PWA stores a farmer assertion locally, obtains a server acknowledgement on reconnect, then routes it to CARE for revalidation.'],['Human-authority CARE','RoR, registry and farmer assertion remain separate. A District Verifier decides; evaluator APIs never mutate Government sources.'],['Purpose consent + deterministic scheme trace','Consent is minimal and revocable; scheme pre-check cannot grant statutory eligibility.'],['Integration truth','Rajasthan and central rails are explicitly labelled sandbox, public reference, contract-ready or live prototype.'],['90-day work-order readiness','The implementation is scoped as a production core + field pilot with measurable acceptance criteria, not an instant statewide replacement claim.']];let walkIndex=0;function showWalk(){const w=WALK[walkIndex];$('#modalStep').textContent=(walkIndex+1)+' / '+WALK.length;$('#modalTitle').textContent=w[0];$('#modalText').textContent=w[1];$('#modalBack').style.visibility=walkIndex?'visible':'hidden';$('#modalNext').textContent=walkIndex===WALK.length-1?'Finish':'Next';$('#modal').classList.add('on')}$('#judgeMode').onclick=()=>{walkIndex=0;showWalk()};$('#modalBack').onclick=()=>{if(walkIndex){walkIndex--;showWalk()}};$('#modalNext').onclick=()=>{if(walkIndex===WALK.length-1)$('#modal').classList.remove('on');else{walkIndex++;showWalk()}};
DISTRICTS.forEach(d=>$('#districtFilter').insertAdjacentHTML('beforeend',`<option>${d}</option>`));renderDistrictOptions();renderAll();hydrate();
